// `patchfly init` — write patchfly.yaml config in the current Flutter project.

import 'dart:io';
import 'package:args/args.dart';
import 'package:path/path.dart' as p;
import '../cli.dart';

class InitCommand implements CommandRunner {
  @override
  String get name => 'init';
  @override
  String get description =>
      'Initialize Patchfly in a Flutter project (writes patchfly.yaml)';

  @override
  Future<void> run(List<String> args) async {
    if (args.isEmpty || args.contains('--help') || args.contains('-h')) {
      _printUsage();
      return;
    }
    final parser = ArgParser()
      ..addFlag('help', abbr: 'h', negatable: false)
      ..addOption('platform',
          allowed: ['android', 'ios', 'all'],
          defaultsTo: 'android',
          help: 'Target platform(s): android, ios, or all')
      ..addOption('app-id', help: 'App ID (slug) registered on server')
      ..addOption('channel', help: 'Default channel (stable/beta/internal)',
          defaultsTo: 'stable')
      ..addOption('abi',
          help: 'Target ABI (arm64-v8a, armeabi-v7a, x86_64). Default: arm64-v8a',
          defaultsTo: 'arm64-v8a')
      ..addFlag('force', abbr: 'f', help: 'Overwrite existing patchfly.yaml');

    final result = parser.parse(args);
    if (result['help'] == true) {
      _printUsage();
      return;
    }

    final cwd = Directory.current;
    final configFile = File(p.join(cwd.path, 'patchfly.yaml'));

    if (await configFile.exists() && !result['force']) {
      throw CliException(
          'patchfly.yaml already exists. Use --force to overwrite.');
    }

    // Try to auto-detect app slug from pubspec.yaml
    String? slug = result['app-id'];
    final pubspec = File(p.join(cwd.path, 'pubspec.yaml'));
    if (slug == null && await pubspec.exists()) {
      try {
        final content = await pubspec.readAsString();
        // Naive parse — look for "name: foo_bar"
        final m = RegExp(r'^name:\s*([^\s#]+)', multiLine: true).firstMatch(content);
        if (m != null) {
          final n = m.group(1)!.trim();
          // Use this as a hint
          slug = n.replaceAll('_', '');
        }
      } catch (_) {}
    }

    final platform = result['platform'] as String;
    final includeAndroid = platform == 'android' || platform == 'all';
    final includeIos = platform == 'ios' || platform == 'all';

    final yaml = '''
# Patchfly configuration. Generated by `patchfly init`.
# Do not commit the api_key or release credentials.

app:
  # slug from `patchfly apps list` or `patchfly apps create`
  slug: ${slug ?? '<your-app-slug>'}

defaults:
  channel: ${result['channel']}
${includeAndroid ? '  abi: ${result['abi']}' : ''}

# AOT output location. The CLI compiles a release build and extracts
# the compiled snapshot to upload as a patch.
build:
${includeAndroid ? '''  # Android: Path to the release APK. The CLI extracts libapp.so.
  apk_path: build/app/outputs/flutter-apk/app-release.apk
  # OR: path to a pre-built libapp.so (advanced)
  # libapp_path: build/app/intermediates/merged_native_libs/release/mergeReleaseNativeLibs/out/lib/arm64-v8a/libapp.so''' : ''}
${includeIos ? '''  # iOS: Path to the App binary inside App.framework.
  ios_app_path: build/ios/iphoneos/Runner.app/Frameworks/App.framework/App''' : ''}
''';

    await configFile.writeAsString(yaml);
    print('✓ Wrote patchfly.yaml');
    print('');
    print('Next steps:');
    print('  1. Edit patchfly.yaml and set your app slug');
    print('  2. Run `patchfly login`');
    print('  3. Run `patchfly apps create` (if you haven\'t registered the app yet)');
    print('  4. Run `patchfly patch` to build & upload a patch');
  }

  void _printUsage() {
    print('''
patchfly init — initialize Patchfly in a Flutter project (writes patchfly.yaml)

Usage:
  patchfly init [options]

Options:
      --platform <name>  Target platform: android | ios | all (default: android)
      --app-id <slug>    App slug registered on the server
      --channel <name>   Default channel: stable | beta | internal (default: stable)
      --abi <name>       Target ABI: arm64-v8a | armeabi-v7a | x86_64 (default: arm64-v8a)
  -f, --force            Overwrite existing patchfly.yaml
  -h, --help             Show this help

Examples:
  patchfly init
  patchfly init --platform ios
  patchfly init --platform all --app-id com.acme.myapp
  patchfly init --platform android --channel beta --abi x86_64
  patchfly init --force  # overwrite existing
''');
  }
}
